version: '3.8'

services:
  # 1. Pythonバックエンドサービス
  app:
    build: .
    restart: always
    expose:
      - "5000"

  # 2. Webサーバー (Nginx) サービス
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80" # VPSの80番ポートをNginxコンテナの80番ポートに接続
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Nginxの設定ファイルを読み込ませる
